version: '2'
services:
  api:
    image: pickledbubble-api
    restart: always
    container_name: ${BE_CONTAINER_NAME}
    restart: always
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_HOST: ${MONGO_CONTAINER_NAME}
      DATABASE_PORT: 27017
      DATABASE_NAME: ${APP_NAME}
      DATABASE_USERNAME: ${APP_NAME}
      DATABASE_PASSWORD: ${APP_NAME}
      PUBLIC_URL: ${PUBLIC_URL}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      NODE_ENV: production
    depends_on:
      - db
    volumes:
      - ./uploads:/srv/app/public/uploads

  ui:
    image: pickledbubble-ui
    restart: always
    container_name: ${FE_CONTAINER_NAME}
    restart: always
    environment:
      API_URL: ${API_URL}
      PUBLIC_URL: ${PUBLIC_URL}
      NODE_ENV: production
      API_PASSWORD: ${API_PASSWORD}
      API_USERNAME: ${API_USERNAME}
    ports:
      - '3011:3000'
    depends_on:
      - api

  db:
    image: mongo
    restart: always
    container_name: ${MONGO_CONTAINER_NAME}
    environment:
      MONGO_INITDB_DATABASE: ${APP_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${APP_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${APP_NAME}
    volumes:
      - ./data:/data/db
